### ISSUE TITLE
"Due to recent changes to the github platform this project has moved to gitlab..."

### ISSUE THREAD

**Issue by Lanchon** [yvesf/andiodine#47]
hi,

> Due to recent changes to the github platform this project has moved to [gitlab.com](https://gitlab.com/andiodine) for hosting.

could you share what changed made you move?

thanks!

**Comment by yvesf** [comment]
I thought the satirical image made it clear :)
It's my perception that the history of the Microsoft company doesn't fit the nature of this app.
You may have seen that I didn't put much effort in to this app recently. If you want to contribute but don't want to use gitlab.com, then you are always welcome use e-mail to communicate with me.
Of course everybody is free to clone this on github.com if it's considered a helpful tool to them. I keep a personal [mirror](https://www.localnet.cc/cgit/yvesf/gitlab.com/andiodine/andiodine.git/) because for projects/apps like this I see platforms like github more as a way to gain visibility than a useful tool.

**Comment by Lanchon** [comment]
oh the MS thing.... things have changed. you know, now that they are not the big fish anymore, they are sort of behaving much better than before. if i had to choose between goog, the fruit company, and micro$oft today, i'd probably go with MS.

that said, the centralization of github is problematic. when it goes down (it will, it's a company), it could take a huge piece of software history with it. in the hands of MS i think there is a better chance of an orderly shutdown than if it were an indie shop with no alternative bets and an all-or-nothing push to survive. who knows...

in the topic of andiodine, i do have gitlab, and i forked a few days ago. i'll issue some PR soon.

thanks!
